---
title: "Your Title Here"
author: "Adelle Sumabat"
date: "8/27/2019"
output: word_document
csl: bioinformatics.csl
bibliography: references.bib
---

# Overview of Proposed Project 

My plan for this semester-long project is to analyze the microbiome of bathroom sinks. I will compare the microbiome of bathroom sinks from residential houses and compare them to the microbiome of sinks in public restrooms. 

Bacteria is found in high concentrations in built environments. Out of all rooms in a built environment, it has been found that bathrooms contain a higher concentration of bacteria than any other room due to bathrooms being a less ventilated room and a much more moist environment. [@ojima2002hygiene] Research has shown that the highest concentration of bacteria in residential homes are found in moist areas such as bathroom sinks. [@rusin1998reduction] Human occupancy and human contact can have an affect on the community of the microbiome of a surface area. [@ramos2014tools] 

This research is important because we spend most of our time indoors and especially in our homes. Being constantly exposed to the bacteria in our homes or public places can greatly influence our health. By knowing how much bacteria is in a certain place we come into close contact with, such as bathroom or restroom sinks, we can then find ways of reducing any contamination that could lead to possible illness. 

# Study Design

I will swab the drains of bathroom sinks from three different homes as well as the drains of restroom sinks in three different public places. After collecting my samples, I will analyze and compare the microbiome I obtained from each sample.

# Question 

The question that I will be working to address is, "Does the number of people getting in contact with a bathroom sink affect the diversity of the microbiome that is found within it?" 

# Hypothesis 

The bathroom sinks in public restrooms will have a more diverse microbiome than the bathroom sinks in a residential home because of the higher number people who  have access to it. 

# Materials  

* 6 sterile cotton swabs 

* 6 sterile tubes with sterile buffer 

* bathroom sinks from three different homes

* bathroom sinks from three different public restrooms

# Methods 

1. I will obtain my samples for this project during lab session on Tuesday, September 3. 
2. Swab the drain of a bathroom sink from my home. 
3. Swab the drain of a bathroom sink in my aunt's home.
4. Swab the drain of a bathroom sink of my grandparent's home.
5. Swab the drain of a restroom sink at my work, Apple Store in Stonestown.
6. Swab the drain of a restroom sink at Starbucks bathroom
7. Swab the drain of a restroom sink at a mall bathroom. 
8. Bring samples to class and begin first step of extracting DNA. 
9. Culture and plate samples in three different dilutions. 